// Generated by gencpp from file cv_bridge0/tennisballs.msg
// DO NOT EDIT!


#ifndef CV_BRIDGE0_MESSAGE_TENNISBALLS_H
#define CV_BRIDGE0_MESSAGE_TENNISBALLS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cv_bridge0/tennisball.h>

namespace cv_bridge0
{
template <class ContainerAllocator>
struct tennisballs_
{
  typedef tennisballs_<ContainerAllocator> Type;

  tennisballs_()
    : header()
    , balls()  {
    }
  tennisballs_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , balls(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::cv_bridge0::tennisball_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cv_bridge0::tennisball_<ContainerAllocator> >::other >  _balls_type;
  _balls_type balls;





  typedef boost::shared_ptr< ::cv_bridge0::tennisballs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cv_bridge0::tennisballs_<ContainerAllocator> const> ConstPtr;

}; // struct tennisballs_

typedef ::cv_bridge0::tennisballs_<std::allocator<void> > tennisballs;

typedef boost::shared_ptr< ::cv_bridge0::tennisballs > tennisballsPtr;
typedef boost::shared_ptr< ::cv_bridge0::tennisballs const> tennisballsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cv_bridge0::tennisballs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cv_bridge0::tennisballs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cv_bridge0

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/lunar/share/sensor_msgs/cmake/../msg'], 'cv_bridge0': ['/home/jbmdumont/catkin_ws/src/cv_bridge0/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cv_bridge0::tennisballs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cv_bridge0::tennisballs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cv_bridge0::tennisballs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cv_bridge0::tennisballs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cv_bridge0::tennisballs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cv_bridge0::tennisballs_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cv_bridge0::tennisballs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "059ef9e5c20be95021f1e65fd5fef3c5";
  }

  static const char* value(const ::cv_bridge0::tennisballs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x059ef9e5c20be950ULL;
  static const uint64_t static_value2 = 0x21f1e65fd5fef3c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::cv_bridge0::tennisballs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cv_bridge0/tennisballs";
  }

  static const char* value(const ::cv_bridge0::tennisballs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cv_bridge0::tennisballs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
cv_bridge0/tennisball[] balls\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cv_bridge0/tennisball\n\
float32 x\n\
float32 y\n\
float32 yellow\n\
";
  }

  static const char* value(const ::cv_bridge0::tennisballs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cv_bridge0::tennisballs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.balls);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tennisballs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cv_bridge0::tennisballs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cv_bridge0::tennisballs_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "balls[]" << std::endl;
    for (size_t i = 0; i < v.balls.size(); ++i)
    {
      s << indent << "  balls[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cv_bridge0::tennisball_<ContainerAllocator> >::stream(s, indent + "    ", v.balls[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CV_BRIDGE0_MESSAGE_TENNISBALLS_H
