set(_CATKIN_CURRENT_PACKAGE "n_led")
set(n_led_VERSION "0.0.0")
set(n_led_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(n_led_PACKAGE_FORMAT "2")
set(n_led_BUILD_DEPENDS "roscpp" "std_msgs")
set(n_led_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(n_led_BUILDTOOL_DEPENDS "catkin")
set(n_led_BUILDTOOL_EXPORT_DEPENDS )
set(n_led_EXEC_DEPENDS "roscpp" "std_msgs")
set(n_led_RUN_DEPENDS "roscpp" "std_msgs")
set(n_led_TEST_DEPENDS )
set(n_led_DOC_DEPENDS )
set(n_led_URL_WEBSITE "")
set(n_led_URL_BUGTRACKER "")
set(n_led_URL_REPOSITORY "")
set(n_led_DEPRECATED "")