set(_CATKIN_CURRENT_PACKAGE "serial_led")
set(serial_led_VERSION "0.0.0")
set(serial_led_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(serial_led_PACKAGE_FORMAT "2")
set(serial_led_BUILD_DEPENDS "rospy" "rosserial_arduino" "rosserial_client" "std_msgs")
set(serial_led_BUILD_EXPORT_DEPENDS "rospy" "rosserial_arduino" "rosserial_client" "std_msgs")
set(serial_led_BUILDTOOL_DEPENDS "catkin")
set(serial_led_BUILDTOOL_EXPORT_DEPENDS )
set(serial_led_EXEC_DEPENDS "rospy" "rosserial_arduino" "rosserial_client" "std_msgs")
set(serial_led_RUN_DEPENDS "rospy" "rosserial_arduino" "rosserial_client" "std_msgs")
set(serial_led_TEST_DEPENDS )
set(serial_led_DOC_DEPENDS )
set(serial_led_URL_WEBSITE "")
set(serial_led_URL_BUGTRACKER "")
set(serial_led_URL_REPOSITORY "")
set(serial_led_DEPRECATED "")