set(_CATKIN_CURRENT_PACKAGE "description")
set(description_VERSION "0.0.0")
set(description_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(description_PACKAGE_FORMAT "2")
set(description_BUILD_DEPENDS )
set(description_BUILD_EXPORT_DEPENDS )
set(description_BUILDTOOL_DEPENDS "catkin")
set(description_BUILDTOOL_EXPORT_DEPENDS )
set(description_EXEC_DEPENDS )
set(description_RUN_DEPENDS )
set(description_TEST_DEPENDS )
set(description_DOC_DEPENDS )
set(description_URL_WEBSITE "")
set(description_URL_BUGTRACKER "")
set(description_URL_REPOSITORY "")
set(description_DEPRECATED "")