set(_CATKIN_CURRENT_PACKAGE "gps0")
set(gps0_VERSION "0.0.0")
set(gps0_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(gps0_PACKAGE_FORMAT "2")
set(gps0_BUILD_DEPENDS "roscpp" "std_msgs")
set(gps0_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(gps0_BUILDTOOL_DEPENDS "catkin")
set(gps0_BUILDTOOL_EXPORT_DEPENDS )
set(gps0_EXEC_DEPENDS "roscpp" "std_msgs")
set(gps0_RUN_DEPENDS "roscpp" "std_msgs")
set(gps0_TEST_DEPENDS )
set(gps0_DOC_DEPENDS )
set(gps0_URL_WEBSITE "")
set(gps0_URL_BUGTRACKER "")
set(gps0_URL_REPOSITORY "")
set(gps0_DEPRECATED "")