// Generated by gencpp from file ledx/modeRequest.msg
// DO NOT EDIT!


#ifndef LEDX_MESSAGE_MODEREQUEST_H
#define LEDX_MESSAGE_MODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ledx
{
template <class ContainerAllocator>
struct modeRequest_
{
  typedef modeRequest_<ContainerAllocator> Type;

  modeRequest_()
    : status(false)
    , id(0)  {
    }
  modeRequest_(const ContainerAllocator& _alloc)
    : status(false)
    , id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::ledx::modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ledx::modeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct modeRequest_

typedef ::ledx::modeRequest_<std::allocator<void> > modeRequest;

typedef boost::shared_ptr< ::ledx::modeRequest > modeRequestPtr;
typedef boost::shared_ptr< ::ledx::modeRequest const> modeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ledx::modeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ledx::modeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ledx

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ledx::modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ledx::modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ledx::modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ledx::modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ledx::modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ledx::modeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ledx::modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8709cd49ae9641b749714ade70054694";
  }

  static const char* value(const ::ledx::modeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8709cd49ae9641b7ULL;
  static const uint64_t static_value2 = 0x49714ade70054694ULL;
};

template<class ContainerAllocator>
struct DataType< ::ledx::modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ledx/modeRequest";
  }

  static const char* value(const ::ledx::modeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ledx::modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n\
int32 id\n\
";
  }

  static const char* value(const ::ledx::modeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ledx::modeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct modeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ledx::modeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ledx::modeRequest_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEDX_MESSAGE_MODEREQUEST_H
