set(_CATKIN_CURRENT_PACKAGE "cv_bridge0")
set(cv_bridge0_VERSION "0.0.0")
set(cv_bridge0_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(cv_bridge0_PACKAGE_FORMAT "2")
set(cv_bridge0_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "message_generation" "std_msgs")
set(cv_bridge0_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "message_generation")
set(cv_bridge0_BUILDTOOL_DEPENDS "catkin")
set(cv_bridge0_BUILDTOOL_EXPORT_DEPENDS )
set(cv_bridge0_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "message_runtime")
set(cv_bridge0_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "message_runtime" "message_generation")
set(cv_bridge0_TEST_DEPENDS )
set(cv_bridge0_DOC_DEPENDS )
set(cv_bridge0_URL_WEBSITE "")
set(cv_bridge0_URL_BUGTRACKER "")
set(cv_bridge0_URL_REPOSITORY "")
set(cv_bridge0_DEPRECATED "")