; Auto-generated. Do not edit!


(cl:in-package servo0-msg)


;//! \htmlinclude angleResult.msg.html

(cl:defclass <angleResult> (roslisp-msg-protocol:ros-message)
  ((res
    :reader res
    :initarg :res
    :type cl:string
    :initform ""))
)

(cl:defclass angleResult (<angleResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <angleResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'angleResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name servo0-msg:<angleResult> is deprecated: use servo0-msg:angleResult instead.")))

(cl:ensure-generic-function 'res-val :lambda-list '(m))
(cl:defmethod res-val ((m <angleResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader servo0-msg:res-val is deprecated.  Use servo0-msg:res instead.")
  (res m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <angleResult>) ostream)
  "Serializes a message object of type '<angleResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'res))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'res))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <angleResult>) istream)
  "Deserializes a message object of type '<angleResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'res) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'res) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<angleResult>)))
  "Returns string type for a message object of type '<angleResult>"
  "servo0/angleResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'angleResult)))
  "Returns string type for a message object of type 'angleResult"
  "servo0/angleResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<angleResult>)))
  "Returns md5sum for a message object of type '<angleResult>"
  "53af918a2a4a2a182c184142fff49b0c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'angleResult)))
  "Returns md5sum for a message object of type 'angleResult"
  "53af918a2a4a2a182c184142fff49b0c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<angleResult>)))
  "Returns full string definition for message of type '<angleResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string res~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'angleResult)))
  "Returns full string definition for message of type 'angleResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string res~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <angleResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'res))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <angleResult>))
  "Converts a ROS message object to a list"
  (cl:list 'angleResult
    (cl:cons ':res (res msg))
))
