set(_CATKIN_CURRENT_PACKAGE "cam0")
set(cam0_VERSION "0.0.0")
set(cam0_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(cam0_PACKAGE_FORMAT "2")
set(cam0_BUILD_DEPENDS "roscpp" "std_msgs")
set(cam0_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(cam0_BUILDTOOL_DEPENDS "catkin")
set(cam0_BUILDTOOL_EXPORT_DEPENDS )
set(cam0_EXEC_DEPENDS "roscpp" "std_msgs")
set(cam0_RUN_DEPENDS "roscpp" "std_msgs")
set(cam0_TEST_DEPENDS )
set(cam0_DOC_DEPENDS )
set(cam0_URL_WEBSITE "")
set(cam0_URL_BUGTRACKER "")
set(cam0_URL_REPOSITORY "")
set(cam0_DEPRECATED "")