(cl:defpackage servo0-msg
  (:use )
  (:export
   "<ANGLEACTION>"
   "ANGLEACTION"
   "<ANGLEACTIONFEEDBACK>"
   "ANGLEACTIONFEEDBACK"
   "<ANGLEACTIONGOAL>"
   "ANGLEACTIONGOAL"
   "<ANGLEACTIONRESULT>"
   "ANGLEACTIONRESULT"
   "<ANGLEFEEDBACK>"
   "ANGLEFEEDBACK"
   "<ANGLEGOAL>"
   "ANGLEGOAL"
   "<ANGLERESULT>"
   "ANGLERESULT"
  ))

