set(_CATKIN_CURRENT_PACKAGE "ledx")
set(ledx_VERSION "0.0.0")
set(ledx_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(ledx_PACKAGE_FORMAT "2")
set(ledx_BUILD_DEPENDS "roscpp" "std_msgs")
set(ledx_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(ledx_BUILDTOOL_DEPENDS "catkin")
set(ledx_BUILDTOOL_EXPORT_DEPENDS )
set(ledx_EXEC_DEPENDS "roscpp" "std_msgs")
set(ledx_RUN_DEPENDS "roscpp" "std_msgs")
set(ledx_TEST_DEPENDS )
set(ledx_DOC_DEPENDS )
set(ledx_URL_WEBSITE "")
set(ledx_URL_BUGTRACKER "")
set(ledx_URL_REPOSITORY "")
set(ledx_DEPRECATED "")