// Generated by gencpp from file servo0/angleFeedback.msg
// DO NOT EDIT!


#ifndef SERVO0_MESSAGE_ANGLEFEEDBACK_H
#define SERVO0_MESSAGE_ANGLEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo0
{
template <class ContainerAllocator>
struct angleFeedback_
{
  typedef angleFeedback_<ContainerAllocator> Type;

  angleFeedback_()
    : feedback(0.0)  {
    }
  angleFeedback_(const ContainerAllocator& _alloc)
    : feedback(0.0)  {
  (void)_alloc;
    }



   typedef float _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::servo0::angleFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo0::angleFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct angleFeedback_

typedef ::servo0::angleFeedback_<std::allocator<void> > angleFeedback;

typedef boost::shared_ptr< ::servo0::angleFeedback > angleFeedbackPtr;
typedef boost::shared_ptr< ::servo0::angleFeedback const> angleFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo0::angleFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo0::angleFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace servo0

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/lunar/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'servo0': ['/home/jbmdumont/catkin_ws/devel_isolated/servo0/share/servo0/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::servo0::angleFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo0::angleFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo0::angleFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo0::angleFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo0::angleFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo0::angleFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo0::angleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d90953f904aa7b8e8d8b4f90a196f18f";
  }

  static const char* value(const ::servo0::angleFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd90953f904aa7b8eULL;
  static const uint64_t static_value2 = 0x8d8b4f90a196f18fULL;
};

template<class ContainerAllocator>
struct DataType< ::servo0::angleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo0/angleFeedback";
  }

  static const char* value(const ::servo0::angleFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo0::angleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
float32 feedback\n\
\n\
";
  }

  static const char* value(const ::servo0::angleFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo0::angleFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angleFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo0::angleFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo0::angleFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<float>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO0_MESSAGE_ANGLEFEEDBACK_H
