set(_CATKIN_CURRENT_PACKAGE "lidar0")
set(lidar0_VERSION "0.0.0")
set(lidar0_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(lidar0_PACKAGE_FORMAT "2")
set(lidar0_BUILD_DEPENDS "rospy" "std_msgs" "sensor_msgs")
set(lidar0_BUILD_EXPORT_DEPENDS "rospy" "std_msgs" "sensor_msgs")
set(lidar0_BUILDTOOL_DEPENDS "catkin")
set(lidar0_BUILDTOOL_EXPORT_DEPENDS )
set(lidar0_EXEC_DEPENDS "rospy" "std_msgs" "sensor_msgs")
set(lidar0_RUN_DEPENDS "rospy" "std_msgs" "sensor_msgs")
set(lidar0_TEST_DEPENDS )
set(lidar0_DOC_DEPENDS )
set(lidar0_URL_WEBSITE "")
set(lidar0_URL_BUGTRACKER "")
set(lidar0_URL_REPOSITORY "")
set(lidar0_DEPRECATED "")