// Generated by gencpp from file n_led/led_on.msg
// DO NOT EDIT!


#ifndef N_LED_MESSAGE_LED_ON_H
#define N_LED_MESSAGE_LED_ON_H

#include <ros/service_traits.h>


#include <n_led/led_onRequest.h>
#include <n_led/led_onResponse.h>


namespace n_led
{

struct led_on
{

typedef led_onRequest Request;
typedef led_onResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct led_on
} // namespace n_led


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n_led::led_on > {
  static const char* value()
  {
    return "d7905a69a29ab5417e659090a623ca63";
  }

  static const char* value(const ::n_led::led_on&) { return value(); }
};

template<>
struct DataType< ::n_led::led_on > {
  static const char* value()
  {
    return "n_led/led_on";
  }

  static const char* value(const ::n_led::led_on&) { return value(); }
};


// service_traits::MD5Sum< ::n_led::led_onRequest> should match 
// service_traits::MD5Sum< ::n_led::led_on > 
template<>
struct MD5Sum< ::n_led::led_onRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n_led::led_on >::value();
  }
  static const char* value(const ::n_led::led_onRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n_led::led_onRequest> should match 
// service_traits::DataType< ::n_led::led_on > 
template<>
struct DataType< ::n_led::led_onRequest>
{
  static const char* value()
  {
    return DataType< ::n_led::led_on >::value();
  }
  static const char* value(const ::n_led::led_onRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n_led::led_onResponse> should match 
// service_traits::MD5Sum< ::n_led::led_on > 
template<>
struct MD5Sum< ::n_led::led_onResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n_led::led_on >::value();
  }
  static const char* value(const ::n_led::led_onResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n_led::led_onResponse> should match 
// service_traits::DataType< ::n_led::led_on > 
template<>
struct DataType< ::n_led::led_onResponse>
{
  static const char* value()
  {
    return DataType< ::n_led::led_on >::value();
  }
  static const char* value(const ::n_led::led_onResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N_LED_MESSAGE_LED_ON_H
