// Generated by gencpp from file n_led/led_onRequest.msg
// DO NOT EDIT!


#ifndef N_LED_MESSAGE_LED_ONREQUEST_H
#define N_LED_MESSAGE_LED_ONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace n_led
{
template <class ContainerAllocator>
struct led_onRequest_
{
  typedef led_onRequest_<ContainerAllocator> Type;

  led_onRequest_()
    : status(false)  {
    }
  led_onRequest_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::n_led::led_onRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::n_led::led_onRequest_<ContainerAllocator> const> ConstPtr;

}; // struct led_onRequest_

typedef ::n_led::led_onRequest_<std::allocator<void> > led_onRequest;

typedef boost::shared_ptr< ::n_led::led_onRequest > led_onRequestPtr;
typedef boost::shared_ptr< ::n_led::led_onRequest const> led_onRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::n_led::led_onRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::n_led::led_onRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace n_led

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::n_led::led_onRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n_led::led_onRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n_led::led_onRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n_led::led_onRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n_led::led_onRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n_led::led_onRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::n_led::led_onRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::n_led::led_onRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::n_led::led_onRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "n_led/led_onRequest";
  }

  static const char* value(const ::n_led::led_onRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::n_led::led_onRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n\
";
  }

  static const char* value(const ::n_led::led_onRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::n_led::led_onRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct led_onRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::n_led::led_onRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::n_led::led_onRequest_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // N_LED_MESSAGE_LED_ONREQUEST_H
