// Generated by gencpp from file led0/mode.msg
// DO NOT EDIT!


#ifndef LED0_MESSAGE_MODE_H
#define LED0_MESSAGE_MODE_H

#include <ros/service_traits.h>


#include <led0/modeRequest.h>
#include <led0/modeResponse.h>


namespace led0
{

struct mode
{

typedef modeRequest Request;
typedef modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mode
} // namespace led0


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::led0::mode > {
  static const char* value()
  {
    return "d7905a69a29ab5417e659090a623ca63";
  }

  static const char* value(const ::led0::mode&) { return value(); }
};

template<>
struct DataType< ::led0::mode > {
  static const char* value()
  {
    return "led0/mode";
  }

  static const char* value(const ::led0::mode&) { return value(); }
};


// service_traits::MD5Sum< ::led0::modeRequest> should match 
// service_traits::MD5Sum< ::led0::mode > 
template<>
struct MD5Sum< ::led0::modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::led0::mode >::value();
  }
  static const char* value(const ::led0::modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::led0::modeRequest> should match 
// service_traits::DataType< ::led0::mode > 
template<>
struct DataType< ::led0::modeRequest>
{
  static const char* value()
  {
    return DataType< ::led0::mode >::value();
  }
  static const char* value(const ::led0::modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::led0::modeResponse> should match 
// service_traits::MD5Sum< ::led0::mode > 
template<>
struct MD5Sum< ::led0::modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::led0::mode >::value();
  }
  static const char* value(const ::led0::modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::led0::modeResponse> should match 
// service_traits::DataType< ::led0::mode > 
template<>
struct DataType< ::led0::modeResponse>
{
  static const char* value()
  {
    return DataType< ::led0::mode >::value();
  }
  static const char* value(const ::led0::modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LED0_MESSAGE_MODE_H
