// Auto-generated. Do not edit!

// (in-package servo0.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class angleGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_angle = null;
    }
    else {
      if (initObj.hasOwnProperty('target_angle')) {
        this.target_angle = initObj.target_angle
      }
      else {
        this.target_angle = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type angleGoal
    // Serialize message field [target_angle]
    bufferOffset = _serializer.float32(obj.target_angle, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type angleGoal
    let len;
    let data = new angleGoal(null);
    // Deserialize message field [target_angle]
    data.target_angle = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'servo0/angleGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd6fd03485afd94bf3f991cd7481101a5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 target_angle
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new angleGoal(null);
    if (msg.target_angle !== undefined) {
      resolved.target_angle = msg.target_angle;
    }
    else {
      resolved.target_angle = 0.0
    }

    return resolved;
    }
};

module.exports = angleGoal;
