// Generated by gencpp from file led1/mode.msg
// DO NOT EDIT!


#ifndef LED1_MESSAGE_MODE_H
#define LED1_MESSAGE_MODE_H

#include <ros/service_traits.h>


#include <led1/modeRequest.h>
#include <led1/modeResponse.h>


namespace led1
{

struct mode
{

typedef modeRequest Request;
typedef modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mode
} // namespace led1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::led1::mode > {
  static const char* value()
  {
    return "d7905a69a29ab5417e659090a623ca63";
  }

  static const char* value(const ::led1::mode&) { return value(); }
};

template<>
struct DataType< ::led1::mode > {
  static const char* value()
  {
    return "led1/mode";
  }

  static const char* value(const ::led1::mode&) { return value(); }
};


// service_traits::MD5Sum< ::led1::modeRequest> should match 
// service_traits::MD5Sum< ::led1::mode > 
template<>
struct MD5Sum< ::led1::modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::led1::mode >::value();
  }
  static const char* value(const ::led1::modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::led1::modeRequest> should match 
// service_traits::DataType< ::led1::mode > 
template<>
struct DataType< ::led1::modeRequest>
{
  static const char* value()
  {
    return DataType< ::led1::mode >::value();
  }
  static const char* value(const ::led1::modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::led1::modeResponse> should match 
// service_traits::MD5Sum< ::led1::mode > 
template<>
struct MD5Sum< ::led1::modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::led1::mode >::value();
  }
  static const char* value(const ::led1::modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::led1::modeResponse> should match 
// service_traits::DataType< ::led1::mode > 
template<>
struct DataType< ::led1::modeResponse>
{
  static const char* value()
  {
    return DataType< ::led1::mode >::value();
  }
  static const char* value(const ::led1::modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LED1_MESSAGE_MODE_H
