; Auto-generated. Do not edit!


(cl:in-package servo0-msg)


;//! \htmlinclude angleGoal.msg.html

(cl:defclass <angleGoal> (roslisp-msg-protocol:ros-message)
  ((target_angle
    :reader target_angle
    :initarg :target_angle
    :type cl:float
    :initform 0.0))
)

(cl:defclass angleGoal (<angleGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <angleGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'angleGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name servo0-msg:<angleGoal> is deprecated: use servo0-msg:angleGoal instead.")))

(cl:ensure-generic-function 'target_angle-val :lambda-list '(m))
(cl:defmethod target_angle-val ((m <angleGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader servo0-msg:target_angle-val is deprecated.  Use servo0-msg:target_angle instead.")
  (target_angle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <angleGoal>) ostream)
  "Serializes a message object of type '<angleGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'target_angle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <angleGoal>) istream)
  "Deserializes a message object of type '<angleGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'target_angle) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<angleGoal>)))
  "Returns string type for a message object of type '<angleGoal>"
  "servo0/angleGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'angleGoal)))
  "Returns string type for a message object of type 'angleGoal"
  "servo0/angleGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<angleGoal>)))
  "Returns md5sum for a message object of type '<angleGoal>"
  "d6fd03485afd94bf3f991cd7481101a5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'angleGoal)))
  "Returns md5sum for a message object of type 'angleGoal"
  "d6fd03485afd94bf3f991cd7481101a5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<angleGoal>)))
  "Returns full string definition for message of type '<angleGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 target_angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'angleGoal)))
  "Returns full string definition for message of type 'angleGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 target_angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <angleGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <angleGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'angleGoal
    (cl:cons ':target_angle (target_angle msg))
))
