set(_CATKIN_CURRENT_PACKAGE "servo0")
set(servo0_VERSION "0.0.0")
set(servo0_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(servo0_PACKAGE_FORMAT "2")
set(servo0_BUILD_DEPENDS "roscpp" "std_msgs" "actionlib" "actionlib_msgs" "message_generation")
set(servo0_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "actionlib_msgs")
set(servo0_BUILDTOOL_DEPENDS "catkin")
set(servo0_BUILDTOOL_EXPORT_DEPENDS )
set(servo0_EXEC_DEPENDS "roscpp" "std_msgs" "actionlib" "actionlib_msgs")
set(servo0_RUN_DEPENDS "roscpp" "std_msgs" "actionlib" "actionlib_msgs")
set(servo0_TEST_DEPENDS )
set(servo0_DOC_DEPENDS )
set(servo0_URL_WEBSITE "")
set(servo0_URL_BUGTRACKER "")
set(servo0_URL_REPOSITORY "")
set(servo0_DEPRECATED "")