set(_CATKIN_CURRENT_PACKAGE "gyro0")
set(gyro0_VERSION "0.0.0")
set(gyro0_MAINTAINER "jbmdumont <jbmdumont@todo.todo>")
set(gyro0_PACKAGE_FORMAT "2")
set(gyro0_BUILD_DEPENDS "roscpp" "std_msgs")
set(gyro0_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(gyro0_BUILDTOOL_DEPENDS "catkin")
set(gyro0_BUILDTOOL_EXPORT_DEPENDS )
set(gyro0_EXEC_DEPENDS "roscpp" "std_msgs")
set(gyro0_RUN_DEPENDS "roscpp" "std_msgs")
set(gyro0_TEST_DEPENDS )
set(gyro0_DOC_DEPENDS )
set(gyro0_URL_WEBSITE "")
set(gyro0_URL_BUGTRACKER "")
set(gyro0_URL_REPOSITORY "")
set(gyro0_DEPRECATED "")